# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PlayerReevoo CICD Deploy Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_SUBSCRIPTION: 13cdb62d-d776-4c96-85b2-5d2d2448ee6f
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.7'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Build & push Docker image to docker
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kenzysc/player-reevoo-image
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Azure Registry
      run: docker login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} springbootapi.azurecr.io
    - name: Build image
      run:  docker build -t springbootapi.azurecr.io/springbootapi:latest .
    - name: Push to Azure Registry
      run:  docker push springbootapi.azurecr.io/springbootapi:latest
    # - name: Login via Azure CLI
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Deploy custom container image
    #   uses: Azure/spring-apps-deploy@v1
    #   with:
    #     azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
    #     action: deploy
    #     service-name: <service instance name>
    #     app-name: <app name>
    #     deployment-name: Microsoft.ContainerRegistry
    #     container-registry: springbootapi.azurecr.io
    #     registry-username: ${{ secrets.AZURE_USERNAME }}
    #     registry-password: ${{ secrets.AZURE_PASSWORD }}
    #     container-image: springbootapi



    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
